---

- hosts: web
  become: true
  tasks:

    - name: Update repository index
      apt:
        update_cache: yes

    - name: Remove Nginx 1.18 package
      apt:
        name: nginx
        state: absent




